In [2]:
import numpy as np

In [6]:
I_Q = np.array([
    [1, -0.6, 0],
    [-0.4, 1, -0.6],
    [0, -0.4, 1]
])

N = np.linalg.inv(I_Q)

S = np.array([
    [0.6, 0, 0],
    [0, 0, 0.4]
])
print(N)

B = S @ N

B 

[[1.46153846 1.15384615 0.69230769]
 [0.76923077 1.92307692 1.15384615]
 [0.30769231 0.76923077 1.46153846]]


array([[0.87692308, 0.69230769, 0.41538462],
       [0.12307692, 0.30769231, 0.58461538]])